updated react to support hooks, converted Game to functional component
elationemr/tic-tac-toe pull request #2
Opened 2021-08-11 20:15 UTC by masciarra

https://elationhealth.atlassian.net/browse/RM-17731

2021-08-11 20:56 UTC, racpa requested changes

2021-08-11 20:56 UTC, racpa commented on package.json
> +    "react-dom": "^17.0.2",
i'm not sold these had to happen, i think staying at react 16 was ok, but we definitely needed to update redux to have access to use hooks

2021-08-11 20:56 UTC, racpa commented on src/utils/operations.js
> +const checkWinner = (board, player, dispatch) => {
proper solution would be to revert all the changes that are happening in this file

2021-08-11 20:56 UTC, racpa commented on src/views/containers/Game.jsx
> +    const hasWinner = checkWinner(board, player, dispatch);
in relation to my other comment throughout this file you should make the appropriate changes where dispatch is used:

the normal way to use `dispatch` would look like:
```
dispatch(checkWinner(board, player))
```

if it's unclear why, i suggest looking up what's happening a bit further in `dispatch` and function currying further

2021-08-12 01:58 UTC, joeybuczek commented on package.json
> +    "react-dom": "^17.0.2",
We need at least React/DOM 16.8.0 or higher, since that's when hooks was officially added. 17 doesn't hurt anything though.

2021-08-13 18:47 UTC, racpa commented on src/views/containers/Game.jsx
> +    let hasWinner = true;
this shouldn't be hard-coded

2021-08-17 14:43 UTC, joeybuczek commented on src/views/containers/Game.jsx
> +    switch (player) {
I feel like the switch is overkill, and you could have simply did something like:

`const nextPlayer = player === 1 ? 2 : 1;`

2021-08-17 18:44 UTC, sidneytang-elation commented on src/actions.js
> +const gameoverAction = () => ({
It's weird to me that this has an "action" suffix in the name when the majority of actions in this file don't. I'd suggest keeping this name as just `gameover` for consistency.

2021-08-17 18:44 UTC, sidneytang-elation commented on src/actions.js
> +const winnerAction = (player) => ({
It's weird to me that this has an "action" suffix in the name when the majority of actions in this file don't. I'd suggest naming this something like `setWinner` (no "action" in the name) for consistency.

2021-08-17 18:44 UTC, sidneytang-elation commented on src/views/containers/Game.jsx
> +  const [showDialog, setShowDialog] = useState(false);
I know `showDialog` was the previous name for this state, but I'd recommend following conventional boolean naming standards (prefixing with `is`/`has`/`should`/etc) while we're here changing the code. E.g.:
```tsx
const [isDialogOpen, setDialogOpen] = useState(false);
```

Personally, I think `showDialog` sounds very much like the name of a function, not a boolean.

2021-08-17 18:45 UTC, sidneytang-elation commented
👀

2021-08-17 19:26 UTC, sidneytang-elation approved these changes

2021-08-17 19:39 UTC, merged